builds:
  -
    goos: [linux, darwin]
    goarch: [386, amd64, arm, arm64]
    ldflags:
    - -s -w -X main.GitSha={{.ShortCommit}} -X main.GitBranch=master -X main.GitTag={{.Version}}
archives:
  - wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: sshportal
    github:
      owner: moul
      name: homebrew-moul
    commit_author:
      name: moul-bot
      email: "m+bot@42.am"
    homepage: https://manfred.life/sshportal
    description: "Simple, fun and transparent SSH (and telnet) bastion"
