apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sshportal.fullname" . }}
  labels:
    {{- include "sshportal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sshportal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sshportal.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:v{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ssh
              containerPort: 2222
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - sshportal
                - healthcheck
                - --quiet
          readinessProbe:
            exec:
              command:
                - sshportal
                - healthcheck
                - --quiet
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- if .Values.mysql.enabled }}
          - name: SSHPORTAL_DATABASE_URL
            value: {{ .Values.mysql.user }}:{{ .Values.mysql.password }}@tcp({{ .Values.mysql.server }}:{{ .Values.mysql.port }})/{{ .Values.mysql.database }}?charset=utf8&parseTime=true&loc=Local
          - name: SSHPORTAL_DB_DRIVER
            value: mysql
          {{- end }}
          {{- if .Values.debug}}
          - name: SSHPORTAL_DEBUG
            value: "1"
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
